#!/usr/bin/env playonlinux-bash
# Date : (2013-02-18)
# Last revision : (2018-02-09 21-39)
# Distribution used to test : Ubuntu 12.10, Ubuntu 16.04
# Author : lahtis
# Licence : retail
# Steam installer.
 
[ -z "$PLAYONLINUX" ] && exit
source "$PLAYONLINUX/lib/sources"
 
PREFIX="terraria"
WORKING_WINE_VERSION="3.1"
TITLE="Terraria"
EDITOR="Merge Games"
GAME_URL="http://www.terraria.org/"
AUTHOR="lahtis"
 
#Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_SetupWindow_SetID 1576
POL_Debug_Init
      
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION" 
STEAM_ID="105600"
Set_OS "win7"
POL_System_TmpCreate "$PREFIX"

# Moving TMP dir
cd "$POL_System_TmpDir"

# Asking about memory size of graphic card
POL_SetupWindow_VMS "512"
 
Poll_Call POL_Function_SetResolution

# Registery fix
cat << EOF > fix.reg
REGEDIT4
       
[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"UseTakeFocus"="Y"
EOF

POL_Wine regedit.exe fix.reg
POL_Wine_WaitExit "$TITLE"

# Installing mandatory dependencies
 
POL_Call POL_Install_xinput # Fix game issue
POL_Call POL_Install_xna40 # Fix game issue
 
# Installing Steam
POL_Call POL_Install_steam
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
POL_Wine "steam.exe" steam://install/$STEAM_ID
POL_Wine_WaitBefore "$TITLE"
      
# Shortcut 
POL_Shortcut "steam.exe" "$TITLE" "$TITLE.png" "steam://rungameid/$STEAM_ID" 

# Check Kernel ptrace
if [ -e "/proc/sys/kernel/yama/ptrace_scope" ]; then
        PTRACE_CHECK=`cat /proc/sys/kernel/yama/ptrace_scope`
        if [ "$PTRACE_CHECK" != 0 ]; then
                POL_Debug_message "$(eval_gettext 'If the game crashes at startup, open a terminal and type:\necho 0|sudo tee /proc/sys/kernel/yama/ptrace_scope')" "$TITLE"
        fi
fi

POL_System_TmpDelete
POL_SetupWindow_Close
exit 0
