#!/bin/bash
# Date : (2013-02-18)
# Last revision : (2013-02-27 01:54)
# Distribution used to test : Ubuntu 12.10
# Author : lahtis
# Licence : retail
# PlayOnLinux: 4.1.9
# Steam installer works (2013-02-18)
 
[-z "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
PREFIX="terraria"
WINEVERSION="1.5.2"
TITLE="Terraria"
EDITOR="Merge Games"
GAME_URL="http://www.terraria.org/"
AUTHOR="lahtis"
 
#Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
      
POL_Debug_Init
      
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WINEVERSION" 
GAME_VMS="512"
STEAM_ID="105600"
 
# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"
 
# Select virtual desktop mode on
Set_Desktop On 1024 768
 
# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS
 
# Installing mandatory dependencies
POL_Call POL_Install_steam
 
# Mandatory pre-install fix for steam
POL_Call POL_Install_steam_flags "$STEAM_ID"
  
# Shortcut done before install for steam version
POL_Shortcut "steam.exe" "$TITLE" "$TITLE.png" "steam://rungameid/$STEAM_ID"
POL_Shortcut "steam.exe" "Steam ($TITLE)" "" ""
 
POL_SetupWindow_message "$(eval_gettext 'Install Terraria in Steam. Run the Terraria when Steam is installed the game. Steam install xna framework the game. Close the Steam so that the installer can continue.')" "$TITLE"
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
POL_Wine start /unix "steam.exe" steam://install/$STEAM_ID
POL_Wine_WaitExit "$TITLE"
      
# Installing mandatory dependencies
 
POL_Call POL_Install_xinput # Fix game issue
POL_Call POL_Install_xna40 # Fix game issue    
 
POL_SetupWindow_message "$(eval_gettext 'If the game crashes at startup, open a terminal and type:\necho 0|sudo tee /proc/sys/kernel/yama/ptrace_scope')"
 
POL_SetupWindow_Close
 
exit 0
