#!/usr/bin/env playonlinux-bash
# Date : (2013-03-01 17-00)
# Last revision : (2018-02-08 23-54)
# Wine version used : 1.5.24
# Distribution used to test : Ubuntu 12.10, Nvidia Geforce 9800 GT 512MB using
# nvidia-experimental-310 driver, Intel® Core™2 Duo CPU E4400 @ 2.00GHz×2, Memory 1,9 GiB
# Author : lahtis lahtis@gmail.com
# Script licence : GPLv2
# Program licence : Retail
# Support France and English CD/DVD-version.
   
# CHANGELOG
# [SuperPlumus] (2013-07-24 09-13)
#   Update gettext messages
#   Clean code
#   Fix POL_Install_directplay call (missing POL_Call)
#   Fix $PLAYONLINUX variable check presence
   
[ -z "$PLAYONLINUX" ] && exit
source "$PLAYONLINUX/lib/sources"
   
TITLE="Freelancer"
PREFIX="Freelancer"
WORKING_WINE_VERSION="3.1"
EDITOR="Microsoft game studios"
GAME_URL="http://www.microsoft.com/games/freelancer/default.aspx"
AUTHOR="lahtis"
   
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_SetupWindow_SetID 1600
POL_Debug_Init
   
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
   
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
POL_System_TmpCreate "$PREFIX"
Set_OS "winxp"
 
POL_SetupWindow_VMS "128"
POL_Call POL_Function_SetResolution
POL_Call POL_Install_directplay
 
 
POL_SetupWindow_menu "What is your language version?" "Languages" "english|french" "|"
LANGUAGEVERSION="$APP_ANSWER"
    if [ "$APP_ANSWER" == "english" ]; then
        SETUPFILE="SETUP.EXE"
            LANG="Install Freelancer."
        elif [ "$APP_ANSWER" == "french" ]; then
        SETUPFILE="install.exe"
            LANG="Programme d'installation Freelancer."    
    fi
 
POL_SetupWindow_cdrom
POL_SetupWindow_check_cdrom "00000000.016"
POL_Wine start /unix "$CDROM/$SETUPFILE"
POL_Wine_WaitExit "$(eval_gettext '$LANG')"
        
POL_Shortcut "Freelancer.exe" "$TITLE" "$TITLE.png"
  
POL_SetupWindow_question "$(eval_gettext 'Do you want to install patch?')" "$TITLE"
if [ "$APP_ANSWER" = "TRUE" ]; then
  
        POL_SetupWindow_InstallMethod "DOWNLOAD,LOCAL"
   
        if [ "$INSTALL_METHOD" = "DOWNLOAD" ]; then
        # Download patch 1.1
        cd "$POL_System_TmpDir"
        POL_Download "http://the-starport.net/freelancer/download/visit.php?cid=1&lid=2639"
   
        # Move file to correct filename
        mv "visit.php?cid=1&lid=2639" "flpatch.zip" || POL_Debug_Fatal "$(eval_gettext 'Error rename the file!')"
           
        # Unzip patch
        unzip "flpatch.zip" || POL_Debug_Fatal "$(eval_gettext 'Error unzip the file!')"
        POL_Wine_WaitBefore "$TITLE"
           
        # Install 1.1 patch
        POL_Wine "$POL_System_TmpDir/flpatch.exe" || POL_Debug_Fatal "$(eval_gettext 'Error file installing!')"
        POL_Wine_WaitExit "$TITLE"
            POL_System_TmpDelete
        fi
          
        if [ "$INSTALL_METHOD" = "LOCAL" ]; then
        cd "$HOME"
        POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run')" "$TITLE"
        SetupFile="$APP_ANSWER"
        POL_Wine_WaitBefore "$TITLE"
        POL_Wine start /unix "$SetupFile"
            fi
          
fi
  
POL_Wine_WaitExit
POL_SetupWindow_Close
exit 0
