#!/bin/bash
# Date : (2015-28-12 21:55)
# Last revision : (2019-04-02 02:46)
# Distribution used to test : Ubuntu 16.04
# Author : lahtis
# Licence : GPLv3
# PlayOnLinux: 4.3.4

[ -z "$PLAYONLINUX" ] && exit 0 
source "$PLAYONLINUX/lib/sources"
 
TITLE="ifolor Designer"
PREFIX="ifolorDesigner"
WORKING_WINE_VERSION="4.0-rc7-staging"
EDITOR=""
GAME_URL="http://www.ifolor.fi/en/ifolor_designer"
AUTHOR="lahtis"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_SetupWindow_message "$(eval_gettext 'If the program crashes at startup, open a terminal and type:\necho 0|sudo tee /proc/sys/kernel/yama/ptrace_scope')"

# Dependencies, overrides, and Windows version settings
POLL_Call POL_Install_dotnet45

# Do you have downloaded the program file?
# Choose XP file.
POL_SetupWindow_question "$(eval_gettext 'Do you have downloaded the program file?')" "$TITLE"
if [ "$APP_ANSWER" = "FALSE" ]
then
	POL_Browser "http://www.ifolor.fi/en/ifolor_designer"
fi

cd "$HOME" ||exit
POL_SetupWindow_browse "$(eval_gettext 'Please select the downloaded program file.')" "$TITLE"

POL_Wine "$APP_ANSWER"
POL_Wine_WaitExit "$TITLE"

POL_Shortcut "Ifolor.DesignCenter.Starter.exe" "$TITLE"

POL_SetupWindow_Close
 
exit 0
 
exit 0
