#!/bin/bash
# Date : (2015-28-12 21:55)
# Last revision : (2015-29-12 01:05)
# Distribution used to test : Ubuntu 14.04
# Author : lahtis
# Licence : GPLv3
# PlayOnLinux: 4.2.8

[ -z "$PLAYONLINUX" ] && exit 0 
source "$PLAYONLINUX/lib/sources"
 
TITLE="Rajala Pro Shop"
PREFIX="RajalaProShop"
WORKING_WINE_VERSION="1.9.4"
EDITOR=""
GAME_URL="http://www.rajalacamera.fi/kuvapalvelut/kuvakirjat"
AUTHOR="lahtis"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Dependencies, overrides, and Windows version settings
POLL_Call POL_Install_dotnet45
POLL_Call POL_Install_gdiplus 

POL_System_TmpCreate "$PREFIX"

# Download and install missing icmui.dll and move C:\Windows\System32\icmui.dll location
cd "$POL_System_TmpDir"
POL_Download "http://www.search-dll.com/download/769.html"

mv "769.html" "$WINEPREFIX/drive_c/windows/system32/icmui.dll"

# Delete temp files
POL_System_TmpDelete

# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"

# Do you have downloaded the program file?
# Choose XP file.
POL_SetupWindow_question "$(eval_gettext 'Do you have downloaded the program file?')" "$TITLE"
if [ "$APP_ANSWER" = "FALSE" ]
then
	POL_Browser "http://www.rajalacamera.fi/kuvapalvelut/kuvakirjat"
fi

POL_SetupWindow_browse "$(eval_gettext 'Please select the downloaded program file.')" "$TITLE"

cd "$HOME" ||exit
POL_Wine "$APP_ANSWER"
POL_Wine_WaitExit "$TITLE"

POL_Shortcut "Rajala Pro Shop.exe" "$TITLE"

POL_SetupWindow_Close
 
exit 0
