#!/bin/bash
# Date : (2013-02-22)
# Last revision : (2013-03-04 16:08)
# Author : lahtis
# PlayOnLinux: 4.1.1
 
[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
TITLE="Poker Stars"
WINEVERSION="1.4.1"
EDITOR="PokerStars"
EDITOR_URL="http://www.pokerstars.eu/"
PREFIX="PokerStarsEU"
 
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$EDITOR_URL" "lahtis" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WINEVERSION"
 
# Create tmp directory for downloaded files
POL_System_TmpCreate "PokerStarsTmp"
 
# Moving tmp directory
cd "$POL_System_TmpDir"
 
# Download file
POL_Download "http://www.pokerstars.net/PokerStarsInstallEU.exe"
 
# Select setup file
SETUP="$POL_System_TmpDir/PokerStarsInstallEU.exe"
 
# Install file && check install errors
POL_Wine "$SETUP" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"
 
# Delete tmp directory
POL_System_TmpDelete
 
# Create shortcut
POL_Shortcut "PokerStars.exe" "$TITLE" "$TITLE.png"
 
# Wait is patch is installed
POL_Wine_WaitExit "$TITLE"
 
POL_SetupWindow_Close
exit 0
