#!/bin/bash
# Date : (2015-28-12 21:55)
# Last revision : (2015-28-12 21:55)
# Distribution used to test : Ubuntu 14.04
# Author : lahtis
# Licence : GPLv3
# PlayOnLinux: 4.2.9
# installer working, settings working but program crash

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
TITLE="BrewMate"
PREFIX="BrewMate"
WORKING_WINE_VERSION="1.8-rc4-staging"
EDITOR=""
GAME_URL="http://www.brewmate.net/"
AUTHOR="lahtis"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

POL_CALL POL_Install_dotnet35

# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"

# Do you have downloaded the game file?
POL_SetupWindow_question "$(eval_gettext 'Do you have downloaded the program file?')" "$TITLE"
if [ "$APP_ANSWER" = "FALSE" ]
then
	POL_Browser "http://www.brewmate.net/"
fi

cd "$HOME"

POL_SetupWindow_browse "$(eval_gettext 'Please select the downloaded program file.')" "$TITLE"
POL_Wine "$APP_ANSWER"
POL_Wine_WaitExit "$TITLE"

POL_Shortcut "brewmate.exe" "$TITLE"

POL_SetupWindow_Close
 
exit 0
