#!/bin/bash
# Date : (2013-06-25 20:43)
# Last revision : (2013-06-25 20:43)
# Wine version used : 1.3.25
# Distribution used to test : Ubuntu 12.10, Nvidia Geforce 9800 GT 512MB using
# nvidia-experimental-310 driver, Intel® Core™2 Duo CPU E4400 @ 2.00GHz×2, Memory 1,9 GiB
# Author : lahtis <lahtis@gmail.com>
# Script licence : GPL v.2
# Program licence : Retail
# Jagged Alliance 2 - retail and git installer
# User is using this installer for coping the all data files in linux native version witch found Ubuntu repository ja2-Stracciatella or Bitbucket git ja2-Straccietella Continued version. This installer install Bitbucket Git ja2-Straccietella Continued patch.

[ -z "$PLAYONLINUX" = "" ] && exit
source "$PLAYONLINUX/lib/sources"

PREFIX="JaggedAlliance2_git"
WORKING_WINE_VERSION="1.3.25"
TITLE="Jagged Alliance 2"
EDITOR="Sir-Tech Software / Strategy First"           
GAME_URL="http://www.jaggedalliance.com/"
AUTHOR="lahtis"
GAME_VMS="512"

# Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init
 
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
Set_OS winxp

# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS

# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"

# Select virtual desktop mode on
Set_Desktop On 800 600
 
# Asking for CDROM and checking if it's correct one
POL_SetupWindow_message "$(eval_gettext 'Please insert the game media into your disk drive')" "$TITLE"
POL_SetupWindow_check_cdrom "install/SETUP.EXE"
POL_SetupWindow_cdrom

POL_Wine start /unix "$CDROM/install/SETUP.EXE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing game.')"
POL_Wine_WaitExit "$TITLE"

# Create tmp directory for downloaded files
POL_System_TmpCreate "$PREFIX"

# Select install method
POL_SetupWindow_InstallMethod "DOWNLOAD"
if [ "$INSTALL_METHOD" == "DOWNLOAD" ]
then

    cd "$POL_System_TmpDir"

    # Download latest ja2-Straccietella Continued files in GIT.
    # version is 0.12.175

    POL_Download "http://ubuntuone.com/5pCsYVOXzXVIOqpPNHFJ3Z"
    POL_SetupWindow_wait "Installation in progress." "$TITLE installation"

    # Move correct filename
    mv "5pCsYVOXzXVIOqpPNHFJ3Z" "ja2-v0.12.175-win.zip"

    # unzip file the correct filepath
    unzip "ja2-v0.12.175-win.zip" "drive_c/Program Files/TalonSoft/Ja2/"

fi

POL_System_TmpDelete



# Create shortcuts adn parameters (ja2.exe -resversion ENGLISH -res 1024x768)
POL_Shortcut "ja2.exe" "$TITLE" "$TITLE.png"
 
POL_SetupWindow_message "$(eval_gettext '$TITLE has been successfully installed.')"
 
POL_SetupWindow_Close
 
exit 0
