#!/bin/bash
# Date : (2013-06-25 20:43)
# Last revision : (2017-01-19 07:06)
# Wine version used : 2.0-rc5-staging
# Distribution used to test : Ubuntu Mate 16.04
# Author : lahtis <lahtis@gmail.com>
# Script licence : GPLv2
# Program version : Retail original CD version
# Bug reports -> https://bugs.winehq.org/show_bug.cgi?id=21008
# Latest install script -> https://github.com/lahtis/playonlinux/blob/master/testing/StarTrekHiddenEvil

[ -z "$PLAYONLINUX" = "" ] && exit
source "$PLAYONLINUX/lib/sources"

PREFIX="StarTrekHiddenEvil"
WORKING_WINE_VERSION="2.0-rc5-staging"
TITLE="Star Trek Hidden Evil"
EDITOR="Aktivision"           
GAME_URL=""
AUTHOR="lahtis"
GAME_VMS="32"

# Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"

POL_SetupWindow_Init
POL_Debug_Init
 
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
Set_OS winxp

# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS

# Fix pulseaudio issue
which pulseaudio && Set_OS "win95"

# Asking for CDROM and checking if it's correct one
POL_SetupWindow_message "$(eval_gettext 'Please insert the game media into your disk drive')" "$TITLE"
POL_SetupWindow_check_cdrom "setup.exe"
POL_SetupWindow_cdrom

POL_Wine start /unix "$CDROM/setup.exe" || POL_Debug_Fatal "$(eval_gettext 'Error while installing game.')"
POL_Wine_WaitExit "$TITLE"

#Game starting file is inside in cd.
#POL_Shortcut "ja2.exe" "$TITLE" "$TITLE.png"
 
POL_SetupWindow_message "$(eval_gettext '$TITLE has been successfully installed.')"
 
POL_SetupWindow_Close
 
exit 0
