#!/bin/bash
# Date : (2017-01-31 16:40)
# Last revision : (2017-01-31 16:40)
# Wine version used : 1.7.37
# Distribution used to test :
# Author : lahtis <lahtis@gmail.com>
# Script licence : GPLv2
# Program version : Retail original CD version
# Latest install script -> https://github.com/lahtis/playonlinux/blob/master/testing/Warcaft3
 
[ -z "$PLAYONLINUX" = "" ] && exit
source "$PLAYONLINUX/lib/sources"
 
PREFIX="Warcaft3"
WORKING_WINE_VERSION="1.7.37"
TITLE="Warcaft 3"
EDITOR="Blizzard Entertainment"          
GAME_URL="http://www.blizzard.com"
AUTHOR="lahtis"
GAME_VMS="256"
 
# Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
 
POL_SetupWindow_Init
POL_Debug_Init
  
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
 
# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS
 
# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"
 
# Asking for CDROM and checking if it's correct one
POL_SetupWindow_message "$(eval_gettext 'Please insert the game media into your disk drive')" "$TITLE"
POL_SetupWindow_check_cdrom "install.exe"
POL_SetupWindow_cdrom
 
POL_Wine start /unix "$CDROM/install.exe" || POL_Debug_Fatal "$(eval_gettext 'Error while installing game.')"
POL_Wine_WaitExit "$TITLE"
 
# Create shortcuts and parameters 
POL_Shortcut "Warcraft III.exe" "$TITLE"
 
POL_SetupWindow_message "$(eval_gettext '$TITLE has been successfully installed.')"
  
POL_SetupWindow_Close
  
exit 0
