#!/bin/bash
# Date : (2016-20-03 17:59)
# Last revision : (2016-20-03 17:59)
# Wine version used : 1.6.2
# Distribution used to test : Ubuntu 14.10
# Author : lahtis lahtis@gmail.com
# Script licence : GPLv.2
# Program licence : Retail
# Depend :
 
[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="Legend of Grimrock (Steam)" 
PREFIX="LegendOfGrimrock"
WORKING_WINE_VERSION="1.6.2"
EDITOR=Almost Human Games 
GAME_URL=http://store.steampowered.com/app/207170/
AUTHOR=lahtis
SHORTCUT_NAME="Legend of Grimrock"
 
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
 
POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
Set_OS winxp

 
POL_Call POL_Install_Steam

# Begin game installation
POL_SetupWindow_menu "$(eval_gettext 'You want install with ?')" "$TITLE" "$(eval_gettext 'Download on Steam Store-Steam Backup Restore')" "-"
 
if [ "$APP_ANSWER" = "$(eval_gettext 'Download on Steam Store')" ]; then
    cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
    POL_Wine "steam.exe" steam://install/207170
    POL_SetupWindow_message "$(eval_gettext 'When $TITLE download by Steam is finished,\nDo NOT click on Play.\n\nClose COMPLETELY the Steam interface, \nso that the installation script can continue.')" "$TITLE"
    POL_Wine_WaitExit "$TITLE"
else
    cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
    POL_Wine "steam.exe"
    POL_SetupWindow_message "$(eval_gettext 'When $TITLE Restore by Steam is finished,\nDo NOT click on Play.\n\nClose COMPLETELY the Steam interface, \nso that the installation script can continue.')" "$TITLE"
    POL_Wine_WaitExit "$TITLE"
fi 
 
POL_Call POL_Install_d3dx9
POL_Call POL_Install_xact
POL_Wine_OverrideDLL builtin d3dx9_43
  
POL_SetupWindow_VMS "256"
 
# Doesn't hurt ;)
POL_Wine_reboot
 
POL_Shortcut "grimrock.exe" "$SHORTCUT_NAME" "$SHORTCUT_NAME.png" "" "Game;RolePlaying;"
 
POL_SetupWindow_Close
 
exit 0
