#!/usr/bin/env playonlinux-bash 
# Date : (2017-01-24)
# Last revision : (2017-01-26 19:57)
# Distribution used to test : Ubuntu 16.04 
# Author : lahtis
# Licence : retail
# PlayOnLinux: 4.2.12
# working 99%, it has unity engine mouse issues.
# This installer pictures files found https://github.com/lahtis/playonlinux/blob/master/working/Subnautica/
 
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
PREFIX="Subnautica"
WINEVERSION="3.0-rc6"
TITLE="Subnautica"
EDITOR="Unknown Worlds"
GAME_URL="https://unknownworlds.com/subnautica/"
AUTHOR="lahtis"
 
# Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init

POL_Debug_Init
      
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x64"
POL_Wine_PrefixCreate "$WINEVERSION" 
STEAM_ID="264710"
Set_OS "win7"
POL_System_TmpCreate "$PREFIX"

# Moving TMP dir
cd "$POL_System_TmpDir"
  
POL_SetupWindow_question "$(eval_gettext 'Do you want to open $TITLE install guide in your browser?')" "$TITLE"

	if [ "$APP_ANSWER" = "TRUE" ] 
	then 
	POL_Browser "https://steamcommunity.com/app/264710/discussions/0/1484358860940334488/"
	fi

# Registery fix
POL_SetupWindow_message "$(eval_gettext 'Modifying register.')" "$TITLE"

cat << EOF > Steam.reg
REGEDIT4
 
[HKEY_CURRENT_USER\Software\Wine\AppDefaults\Steam.exe]
"Version"="winxp64"
EOF

POL_Wine regedit.exe steam.reg

cat << EOF > steamwebhelper.reg
REGEDIT4
 
[HKEY_CURRENT_USER\Software\Wine\AppDefaults\steamwebhelper.exe]
"Version"="winxp64"
EOF

POL_Wine regedit.exe steamwebhelper.reg

POL_Wine_WaitExit "$TITLE"
 
# Installing mandatory dependencies
POL_Call POL_Install_vcrun2013
POL_Call POL_Install_corefonts


# Installing Steam
POL_Call POL_Install_steam
 
POL_SetupWindow_message "$(eval_gettext 'Install $TITLE in Steam. Run the $TITLE when Steam is installed the game.')" "$TITLE"
cd "$WINEPREFIX/drive_c/$PROGRAMFILES/Steam"
POL_Wine "steam.exe" steam://install/$STEAM_ID -no-cef-sandbox
POL_Wine_WaitBefore "$TITLE"

# Shortcut done before install for steam version
POL_Shortcut "steam.exe" "$TITLE (Steam)" "$TITLE.png" "steam://rungameid/$STEAM_ID"
      
POL_SetupWindow_message "$(eval_gettext 'If the game crashes at startup, open a terminal and type:\necho 0|sudo tee /proc/sys/kernel/yama/ptrace_scope')"

POL_SetupWindow_message "$(eval_gettext 'When running game add -force-glcore or -force-opengl\nto your launch options by right clicking the game under Properties, Launch Options.\nNewer Nvidia Proprietary Drivers will work with -force-glcore45, which is OpenGL 4.5.')" "$TITLE"
 
POL_System_TmpDelete
POL_SetupWindow_Close
 
exit 0
