#!/bin/bash
# Date : (2013-02-22 00-08)
# Last revision : (2013-07-24 18-09)
# Wine version used : 1.5.24
# Distribution used to test : Ubuntu 12.10, Nvidia Geforce 9800 GT 512MB using
# nvidia-experimental-310 driver, Intel® Core™2 Duo CPU E4400 @ 2.00GHz×2, Memory 1,9 GiB
# Author : lahtis <lahtis@gmail.com>
# Script licence : GPL v.2
# Program licence : Retail
# Red Faction installer and 1.20 patching.
 
# CHANGELOG
# [SuperPlumus] (2013-07-24 18-09)
#   Update gettext messages
#   Clean code
#   Fix $PLAYONLINUX check
#   Remove duplicate Set_OS winxp
#   Disable InstallMethod "DOWNLOAD" for patch because irregular URL (ubuntuone.com)
 
[ -z "$PLAYONLINUX" ] && exit
source "$PLAYONLINUX/lib/sources"
 
TITLE="Red Faction"
PREFIX="RedFaction1"
WORKING_WINE_VERSION="1.5.24"
EDITOR="Volition / THQ"
GAME_URL="http://community.redfaction.com"
AUTHOR="lahtis"
 
# Initialization
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
 
POL_SetupWindow_Init
POL_Debug_Init
 
# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
# Create Prefix
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
 
POL_System_TmpCreate "$PREFIX"
 
Set_OS "winxp"
POL_SetupWindow_VMS "256"
Set_Desktop "On" "1024" "768"
 
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run')" "$TITLE"
POL_Wine_WaitBefore "$TITLE"
POL_Wine start /unix "$APP_ANSWER"
POL_Wine_WaitExit "$TITLE"
 
# Patching latest 1.20 patch
POL_SetupWindow_message "Install patch 1.20" "$TITLE"
 
POL_SetupWindow_InstallMethod "LOCAL"
if [ "$INSTALL_METHOD" = "LOCAL" ]; then
    cd "$HOME"
    POL_SetupWindow_browse "$(eval_gettext 'Select patch to execute')" "$TITLE" ""
    POL_Wine start /unix "$APP_ANSWER"
    POL_Wine_WaitExit
else
    # Moving tmp directory
    cd "$POL_System_TmpDir"
 
    # Download patch
    POL_Download "http://ubuntuone.com/5ptskYTFkuw6rAMARlIcjn" "6ba17ce7462a59fee85f4f69b2651fe6"
 
    # Move file to correct filename
    mv 5ptskYTFkuw6rAMARlIcjn RedFactionPatch.zip
 
    # Unzip file
    unzip "RedFactionPatch.zip"
 
    # Select setup file
    ARCHIVE="$POL_System_TmpDir/setup.exe"
 
    POL_Wine_WaitBefore "$TITLE"
    POL_Wine "$ARCHIVE"
    POL_Wine_WaitExit "$TITLE"
fi
 
POL_Shortcut "RedFaction.exe" "$TITLE" "$TITLE.png"
POL_Shortcut "RF.exe" "Red Faction editor" "$TITLE.png"
 
POL_SetupWindow_message "$(eval_gettext 'If the game crashes at startup, open a terminal and type:\necho 0|sudo tee /proc/sys/kernel/yama/ptrace_scope')"
 
POL_System_TmpDelete
 
POL_SetupWindow_Close
 
exit 0
