#!/bin/bash
# Date : (2013-03-01 17-00)
# Last revision : (2013-07-24 09-13)
# Wine version used : 1.5.24
# Distribution used to test : Ubuntu 12.10, Nvidia Geforce 9800 GT 512MB using
# nvidia-experimental-310 driver, Intel® Core™2 Duo CPU E4400 @ 2.00GHz×2, Memory 1,9 GiB
# Author : lahtis lahtis@gmail.com
# Script licence : GPL v.2
# Program licence : Retail
# Freelancer installer and 1.1 offical patching.
 
# CHANGELOG
# [SuperPlumus] (2013-07-24 09-13)
#   Update gettext messages
#   Clean code
#   Fix POL_Install_directplay call (missing POL_Call)
#   Fix $PLAYONLINUX variable check presence
 
[ -z "$PLAYONLINUX" ] && exit
source "$PLAYONLINUX/lib/sources"
 
TITLE="Freelancer"
PREFIX="Freelancer"
WORKING_WINE_VERSION="1.5.24"
SERVERTITLE="FreelanceServer"
EDITOR="Microsoft game studios"
GAME_URL="http://www.microsoft.com/games/freelancer/default.aspx"
AUTHOR="lahtis"
GAME_VMS="512"
 
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
 
POL_System_TmpCreate "$PREFIX"
 
POL_SetupWindow_VMS $GAME_VMS
 
Set_OS "winxp"
Set_Desktop "On" "800" "600"
 
POL_Call POL_Install_directplay
 
POL_SetupWindow_cdrom
POL_SetupWindow_check_cdrom "00000000.016"
POL_Wine start /unix "$CDROM/SETUP.EXE"
POL_Wine_WaitExit "$TITLE"
 
POL_Shortcut "Freelancer.exe" "$TITLE" "$TITLE.png"
 
# Install patch 1.1
cd "$POL_System_TmpDir"
# POL_Download "http://download.microsoft.com/download/5/4/2/542a372f-d540-468d-a653-2cdced8d1d0d/flpatch.exe" "b2621b2a33c519d8b599cb3579be4c02"
POL_Download "http://the-starport.net/freelancer/download/visit.php?cid=1&lid=2639"
unzip flpatch.zip

POL_Wine_WaitBefore "$TITLE - Patch 1.1"
POL_Wine "$POL_System_TmpDir/flpatch.exe"
POL_Wine_WaitExit "$TITLE - Patch 1.1"
 
POL_Shortcut "FLServer.exe" "$TITLE server" "$SERVERTITLE.png"
# End install patch 1.1
 
POL_System_TmpDelete
 
POL_SetupWindow_Close
 
exit 0
