#!/bin/bash
# Date : (2014-09-14 16:25)
# Last revision : (2014-09-14 16:25)
# Wine version used : 1.7.26 (PlayOnLinux)
# Distribution used to test : Ubuntu 12.04 x64
# Author : lahtis
# Licence : Retail

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
TITLE="Kuvat Kirjaksi"
PREFIX="kuvatkirjaksi"
EDITOR="Grano Oy"
GAME_URL="http://www.kuvatkirjaksi.fi/"
AUTHOR="lahtis"
WORKING_WINE_VERSION="1.7.26"

# Starting the script
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init

# Starting debugging API
POL_Debug_Init

# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

# Check Kernel ptrace
if [ -e "/proc/sys/kernel/yama/ptrace_scope" ]; then
PTRACE_CHECK=`cat /proc/sys/kernel/yama/ptrace_scope`
   if [ "$PTRACE_CHECK" != 0 ]; then
   POL_Debug_message "$(eval_gettext 'The program will fail to launch until you set /proc/sys/kernel/yama/ptrace_scope to 0')" "$TITLE"
   fi
fi

# Setting prefix path
POL_Wine_SelectPrefix "$PREFIX"

# Downloading wine if necessary and creating prefix
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"

# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS

# Install fonts
POL_Install_corefonts

POL_System_TmpCreate "$PREFIX"

# Download and install the game
cd "$POL_System_TmpDir"

POL_Download "http://www.kuvatkirjaksi.fi/wp-content/uploads/kuvatkirjaksi.exe"

POL_Wine start /unix "$POL_System_TmpDir/kuvatkirjaksi.exe"
POL_Wine_WaitExit "$TITLE"
POL_System_TmpDelete
POL_Shortcut 'Kuvatkirjaksi.exe' "Kuvat kirjaksi"
POL_SetupWindow_Close
exit 0
