#!/bin/bash
# Date : (2017-01-22 19:05)
# Last revision : (2017-01-22 19:05)
# Wine version used : 1.5.24
# Distribution used to test : Ubuntu 16.04 LTS, 32-bit
# Author : lahtis lahtis@gmail.com
# Script licence : GPLv2
# Outpost 2 installer (2-CD)
# Latest installer version -> https://github.com/lahtis/playonlinux/blob/master/working/Outpost2

[ -z "$PLAYONLINUX" ] && exit
source "$PLAYONLINUX/lib/sources"
 
TITLE="Outpost 2: Divided Destiny"
PREFIX="Outpost2"
WORKING_WINE_VERSION="1.2"
EDITOR="Dynamix / Sierra Entertainment"
GAME_URL="http://www.outpost2.net/outpost2.html"
AUTHOR="lahtis"
GAME_VMS="32"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
POL_SetupWindow_VMS "$GAME_VMS"

# Fix pulseaudio issue
which pulseaudio && Set_OS "win95"

POL_SetupWindow_cdrom
POL_SetupWindow_check_cdrom "SETUP.EXE"
POL_Wine start /unix "$CDROM/SETUP.EXE"
POL_Wine_WaitExit "$TITLE"
 
POL_Shortcut "Outpost2.exe" "$TITLE" "$TITLE.png"
 
POL_SetupWindow_Close
 
exit 0
