#!/bin/bash
# Date : (2013-02-26 ??-??)
# Last revision : (2013-07-24 09-37)
# Distribution used to test : Ubuntu 12.10
# Author : lahtis
# Licence : GPLv3
# Installer for Pro pilkki 2 v1.0.3
# PlayOnLinux: 4.1.9, 4.2.1
 
# CHANGELOG
# [SuperPlumus] (2013-07-24 09-37)
#   Update gettext messages
#   Clean code
#   Fix $PLAYONLINUX check presence
 
[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
TITLE="Pro Pilkki 2"
PREFIX="ProPilkki2"
WORKING_WINE_VERSION="1.5.28"
EDITOR="Team Procyon"
GAME_URL="http://www.kalassa.net/propilkki2/index.php?eng=1"
AUTHOR="lahtis"
GAME_VMS="512"
 
 
POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
 
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
 
POL_Wine_SelectPrefix "$PREFIX"
POL_System_SetArch "x86"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"
 
POL_System_TmpCreate "$PREFIX"
 
# Fix pulseaudio issue
which pulseaudio && Set_OS "winxp"
 
# Asking about memory size of graphic card
POL_SetupWindow_VMS $GAME_VMS
 
cd "$POL_System_TmpDir"
POL_Download "http://www.kalassa.net/propilkki2/download/PP2_download.php?id=0" "293f9e4e4ba0905f7f9526042510c2d1"
 
# Move file to correct filename
mv "PP2_download.php?id=0" "P2Installer_v1.0.3.exe"
 
POL_Wine_WaitBefore "$TITLE"
POL_Wine "$POL_System_TmpDir/P2Installer_v1.0.3.exe"
POL_Wine_WaitExit "$TITLE"
 
POL_System_TmpDelete
 
POL_Shortcut 'ProPilkki2.exe' "$TITLE"
 
POL_SetupWindow_Close
 
exit 0
