#!/bin/bash
[ -z "$PLAYONLINUX" ]  && exit 0
source "$PLAYONLINUX/lib/sources"

TITLE="Unity 3D"
PREFIX="Unity3D"
WORKING_WINE_VERSION="1.7.42"
EDITOR="Unity"
GAME_URL="http://www.unity3d.com/"
AUTHOR="Cauê Waneck, lahtis"
GAME_VMS="512"

POL_GetSetupImages "http://files.playonlinux.com/resources/setups/$PREFIX/top.jpg" "http://files.playonlinux.com/resources/setups/$PREFIX/left.jpg" "$TITLE"
POL_SetupWindow_Init
POL_Debug_Init
      
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"
      
# Create prefix
export WINEARCH="win32"
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

# Setup prefix
POL_Wine_InstallFonts
#POL_Call POL_Install_directx9
POL_Call POL_Install_dotnet20
POL_Call POL_Install_tahoma
POL_Call POL_Install_dotnet40
POL_Call POL_Install_d3dx9
POL_Call POL_Install_Flashplayer_ActiveX  # DEwrong md5-sum
POL_Call POL_Install_gdiplus
POL_Call POL_Install_ie8
      
mkdir -p "$WINEPREFIX/drive_c/users/$USER/AppData/LocalLow"
      
# Registry
regfile=$(mktemp --suffix=.REG)
echo "REGEDIT4" > "$regfile"
echo "" >> "$regfile"
echo "[HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion]" >> "$regfile"
echo '"ProductId"="12345-oem-0000001-54321"' >> "$regfile"
      
POL_Wine regedit "$regfile"

# Do you have downloaded the installer?
POL_SetupWindow_question "$(eval_gettext 'Do you have downloaded installer?')" "$TITLE"
if [ "$APP_ANSWER" = "FALSE" ]
then
	POL_Browser "http://unity3d.com/get-unity"
fi
      
POL_SetupWindow_browse "$(eval_gettext 'Please select the location of the Unity3D setup executable')" "Unity Setup Executable"
      
UNITYLOC=$APP_ANSWER
POL_Wine "$UNITYLOC"
      
POL_Shortcut "Unity.exe" "Unity 3D"
      
POL_SetupWindow_Close
 
exit 0
