#!/bin/bash
# Date : (2018-02-11 21-07)
# Last revision : (2018-02-11 21-07)
# Wine version used : 1.3.9
# Distribution used to test : Ubuntu
# Author : lahtis
# Licence : Retail
  
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
PREFIX="JA2-test"
WORKINGWINEVERSION="3.1"


# Do you want to install the patch?
POL_SetupWindow_question "$(eval_gettext 'Do you want to install the patch?')" "$TITLE"
if [ "$APP_ANSWER" = "TRUE" ]
then
	POL_SetupWindow_InstallMethod "DOWNLOAD,LOCAL"
    if [ "$INSTALL_METHOD" == "LOCAL" ]; then
      POL_SetupWindow_browse "$(eval_gettext 'Select patch to execute')" "$TITLE" ""
      POL_Wine start /unix "$APP_ANSWER"
      POL_Wine_WaitExit "$TITLE"
    elif
  
    fi
fi

POL_SetupWindow_Close
exit 0
